"""workspace-scoped, idempotent alerts (alert_generation)

Revision ID: 0009
Revises: 0008
Create Date: 2026-06-21

Reworks alerting from a global ``alerts`` (content) + ``workspace_alerts``
(per-workspace read/dismiss state) split into a single **workspace-scoped**
``alerts`` table that the `alert_generation` worker writes idempotently.

* drops ``workspace_alerts`` (read/dismiss/resolve state now lives on the alert
  row: ``status`` + ``read_at`` / ``dismissed_at`` / ``resolved_at``);
* drops and recreates ``alerts`` with: ``workspace_id`` (now mandatory, scoped),
  ``status``, ``source``, ``related_entity_type`` / ``related_entity_id`` and
  typed ``related_*`` FKs (fund / fund_listing / document_snapshot / job_run),
  a ``dedupe_key`` for idempotency, ``first_seen_at`` / ``last_seen_at`` /
  ``resolved_at`` and a ``raw_payload_json`` provenance blob;
* adds the ``uq_alert_workspace_dedupe`` unique constraint on
  ``(workspace_id, dedupe_key)`` so re-running the generator updates the existing
  alert (``last_seen_at``) instead of inserting a duplicate.

The old ``alerts`` rows were placeholder seed content with no workspace, so they
are intentionally not migrated — alerts are now derived data, regenerated by the
worker. Apply with ``uv run alembic upgrade head``.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_NOW = sa.text("now()")


def upgrade() -> None:
    # Old per-workspace state table + global alert content go away.
    op.drop_index("ix_workspace_alerts_alert_id", table_name="workspace_alerts")
    op.drop_index("ix_workspace_alerts_workspace_id", table_name="workspace_alerts")
    op.drop_table("workspace_alerts")

    op.drop_index("ix_alerts_fund_id", table_name="alerts")
    op.drop_table("alerts")

    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "workspace_id",
            sa.Integer(),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="active"),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("related_entity_type", sa.String(length=32), nullable=True),
        sa.Column("related_entity_id", sa.String(length=64), nullable=True),
        sa.Column(
            "related_fund_id",
            sa.Integer(),
            sa.ForeignKey("funds.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "related_fund_listing_id",
            sa.Integer(),
            sa.ForeignKey("fund_listings.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "related_document_snapshot_id",
            sa.Integer(),
            sa.ForeignKey("document_snapshots.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "related_job_run_id",
            sa.Integer(),
            sa.ForeignKey("job_runs.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_payload_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.UniqueConstraint("workspace_id", "dedupe_key", name="uq_alert_workspace_dedupe"),
    )
    op.create_index("ix_alerts_workspace_id", "alerts", ["workspace_id"])
    op.create_index("ix_alerts_related_fund_id", "alerts", ["related_fund_id"])
    op.create_index("ix_alerts_related_fund_listing_id", "alerts", ["related_fund_listing_id"])


def downgrade() -> None:
    op.drop_index("ix_alerts_related_fund_listing_id", table_name="alerts")
    op.drop_index("ix_alerts_related_fund_id", table_name="alerts")
    op.drop_index("ix_alerts_workspace_id", table_name="alerts")
    op.drop_table("alerts")

    # Restore the previous global alerts + workspace_alerts split.
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "fund_id",
            sa.Integer(),
            sa.ForeignKey("funds.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
    )
    op.create_index("ix_alerts_fund_id", "alerts", ["fund_id"])

    op.create_table(
        "workspace_alerts",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "workspace_id",
            sa.Integer(),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "alert_id",
            sa.Integer(),
            sa.ForeignKey("alerts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_dismissed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.UniqueConstraint("workspace_id", "alert_id", name="uq_workspace_alert"),
    )
    op.create_index("ix_workspace_alerts_workspace_id", "workspace_alerts", ["workspace_id"])
    op.create_index("ix_workspace_alerts_alert_id", "workspace_alerts", ["alert_id"])
